//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minion.depreciated.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Java : global::System.Configuration.ApplicationSettingsBase {
        
        private static Java defaultInstance = ((Java)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Java())));
        
        public static Java Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\fs1\\HelpDesk\\PLUGINS\\Uninstallers\\javara\\")]
        public string RA_Location {
            get {
                return ((string)(this["RA_Location"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-h -accepteula -dfr c:\\temp\\Javara\\JavaRa.exe /uninstallall /silent")]
        public string RA_Uninstall {
            get {
                return ((string)(this["RA_Uninstall"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\fs1\\HelpDesk\\PLUGINS\\JAVA_51_MSI")]
        public string MSI_51_Location {
            get {
                return ((string)(this["MSI_51_Location"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -s -i 1 -realtime msiexec /i c:\\temp\\JAVA_51_MSI\\jre1.7.0_51.msi /qr " +
            " JAVAUPDATE=0 JU=0 AUTOUPDATECHECK=0")]
        public string MSI_51_Argument {
            get {
                return ((string)(this["MSI_51_Argument"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\temp\\JAVA_51_MSI")]
        public string MSI_51_Target {
            get {
                return ((string)(this["MSI_51_Target"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Java")]
        public string Name {
            get {
                return ((string)(this["Name"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\temp\\JavaRA")]
        public string RA_Target {
            get {
                return ((string)(this["RA_Target"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -realtime -i 1 -s -c -f -csrc \"\\\\fs1\\HelpDesk\\PLUGINS\\jre-7u51-window" +
            "s-i586.exe\" jre-7u51-windows-i586.exe")]
        public string Install_51_Manual {
            get {
                return ((string)(this["Install_51_Manual"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-i -h -s c:\\temp\\Javara\\JavaRa.exe /purge")]
        public string RA_Purge {
            get {
                return ((string)(this["RA_Purge"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -i 1 -realtime -h wmic product where \"name like \'Java%%\'\" call uninst" +
            "all /NOINTERACTIVE")]
        public string uninstall_SEARCH {
            get {
                return ((string)(this["uninstall_SEARCH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\fs1\\HelpDesk\\PLUGINS\\JAVA_45_MSI")]
        public string MSI_45_Location {
            get {
                return ((string)(this["MSI_45_Location"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\fs1\\HelpDesk\\PLUGINS\\JAVA_40_MSI")]
        public string MSI_40_Location {
            get {
                return ((string)(this["MSI_40_Location"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -realtime -i 1 -s -c -f -csrc \"\\\\fs1\\HelpDesk\\PLUGINS\\jre-7u45-window" +
            "s-i586.exe\" jre-7u45-windows-i586.exe")]
        public string Install_45_Manual {
            get {
                return ((string)(this["Install_45_Manual"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -realtime -i 1 -s -c -f -csrc \"\\\\fs1\\HelpDesk\\PLUGINS\\jre-7u40-window" +
            "s-i586.exe\" jre-7u40-windows-i586.exe")]
        public string Install_40_Manual {
            get {
                return ((string)(this["Install_40_Manual"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -i 1 -s -realtime msiexec /i c:\\temp\\JAVA_45_MSI\\jre1.7.0_45.msi /qr " +
            "JAVAUPDATE=0 JU=0 AUTOUPDATECHECK=0")]
        public string MSI_45_Argument {
            get {
                return ((string)(this["MSI_45_Argument"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -i 1 -s -realtime msiexec /i c:\\temp\\JAVA_40_MSI\\jre1.7.0_40.msi /qr " +
            "JAVAUPDATE=0 JU=0 AUTOUPDATECHECK=0")]
        public string MSI_40_Argument {
            get {
                return ((string)(this["MSI_40_Argument"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\temp\\JAVA_45_MSI")]
        public string MSI_45_Target {
            get {
                return ((string)(this["MSI_45_Target"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\temp\\JAVA_40_MSI")]
        public string MSI_40_Target {
            get {
                return ((string)(this["MSI_40_Target"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -i 1 -realtime -s msiexec.exe /x {26A24AE4-039D-4CA4-87B4-2F83217051F" +
            "F} /qr")]
        public string uninstall_51 {
            get {
                return ((string)(this["uninstall_51"]));
            }
            set {
                this["uninstall_51"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -i 1 -realtime -s msiexec.exe /x {26A24AE4-039D-4CA4-87B4-2F83217045F" +
            "F} /qr")]
        public string uninstall_45 {
            get {
                return ((string)(this["uninstall_45"]));
            }
            set {
                this["uninstall_45"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -i 1 -realtime -s msiexec.exe /x {26A24AE4-039D-4CA4-87B4-2F83217040F" +
            "F} /qr")]
        public string uninstall_40 {
            get {
                return ((string)(this["uninstall_40"]));
            }
            set {
                this["uninstall_40"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -i 1 -realtime -s msiexec.exe /X {26A24AE4-039D-4CA4-87B4-2F83217025F" +
            "F} /qr")]
        public string uninstall_25 {
            get {
                return ((string)(this["uninstall_25"]));
            }
            set {
                this["uninstall_25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -i 1 -realtime -s msiexec.exe /X {26A24AE4-039D-4CA4-87B4-2F83217025F" +
            "F} /qr")]
        public string uninstall_21 {
            get {
                return ((string)(this["uninstall_21"]));
            }
            set {
                this["uninstall_21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -i 1 -realtime -s msiexec.exe /X {26A24AE4-039D-4CA4-87B4-2F83217017F" +
            "F} /qr")]
        public string uninstall_17 {
            get {
                return ((string)(this["uninstall_17"]));
            }
            set {
                this["uninstall_17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -i 1 -realtime -s msiexec.exe /X {26A24AE4-039D-4CA4-87B4-2F83217016F" +
            "F} /qr")]
        public string uninstall_16 {
            get {
                return ((string)(this["uninstall_16"]));
            }
            set {
                this["uninstall_16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -i 1 -realtime -s msiexec.exe /X {26A24AE4-039D-4CA4-87B4-2F83217015F" +
            "F} /qr")]
        public string uninstall_15 {
            get {
                return ((string)(this["uninstall_15"]));
            }
            set {
                this["uninstall_15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -i 1 -realtime -s msiexec.exe /X {26A24AE4-039D-4CA4-87B4-2F83217015F" +
            "F} /qr")]
        public string uninstall_14 {
            get {
                return ((string)(this["uninstall_14"]));
            }
            set {
                this["uninstall_14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -i 1 -realtime -s msiexec.exe /X {26A24AE4-039D-4CA4-87B4-2F83217015F" +
            "F} /qr")]
        public string uninstall_13 {
            get {
                return ((string)(this["uninstall_13"]));
            }
            set {
                this["uninstall_13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -i 1 -realtime -s msiexec.exe /X {26A24AE4-039D-4CA4-87B4-2F83217012F" +
            "F} /qr")]
        public string uninstall_12 {
            get {
                return ((string)(this["uninstall_12"]));
            }
            set {
                this["uninstall_12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -i 1 -realtime -s msiexec.exe /X {26A24AE4-039D-4CA4-87B4-2F83217011F" +
            "F} /qr")]
        public string uninstall_11 {
            get {
                return ((string)(this["uninstall_11"]));
            }
            set {
                this["uninstall_11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -i 1 -realtime -s msiexec.exe /X {26A24AE4-039D-4CA4-87B4-2F83217010F" +
            "F} /qr")]
        public string uninstall_10 {
            get {
                return ((string)(this["uninstall_10"]));
            }
            set {
                this["uninstall_10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -i 1 -realtime -s msiexec.exe /X {26A24AE4-039D-4CA4-87B4-2F83217009F" +
            "F} /qr")]
        public string uninstall_09 {
            get {
                return ((string)(this["uninstall_09"]));
            }
            set {
                this["uninstall_09"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -i 1 -realtime -s msiexec.exe /X {26A24AE4-039D-4CA4-87B4-2F83217008F" +
            "F} /qr")]
        public string uninstall_08 {
            get {
                return ((string)(this["uninstall_08"]));
            }
            set {
                this["uninstall_08"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -i 1 -realtime -s msiexec.exe /X {26A24AE4-039D-4CA4-87B4-2F83217007F" +
            "F} /qr")]
        public string uninstall_07 {
            get {
                return ((string)(this["uninstall_07"]));
            }
            set {
                this["uninstall_07"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -i 1 -realtime -s msiexec.exe /x {26A24AE4-039D-4CA4-87B4-2F83217006F" +
            "F} /qr")]
        public string uninstall_06 {
            get {
                return ((string)(this["uninstall_06"]));
            }
            set {
                this["uninstall_06"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -i 1 -realtime -s msiexec.exe /X {26A24AE4-039D-4CA4-87B4-2F83217005F" +
            "F} /qr")]
        public string uninstall_05 {
            get {
                return ((string)(this["uninstall_05"]));
            }
            set {
                this["uninstall_05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -i 1 -realtime -s msiexec.exe /x {26A24AE4-039D-4CA4-87B4-2F83217004F" +
            "F} /qr")]
        public string uninstall_04 {
            get {
                return ((string)(this["uninstall_04"]));
            }
            set {
                this["uninstall_04"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -i 1 -realtime -s msiexec.exe /x {26A24AE4-039D-4CA4-87B4-2F83217003F" +
            "F} /qr")]
        public string uninstall_03 {
            get {
                return ((string)(this["uninstall_03"]));
            }
            set {
                this["uninstall_03"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -i 1 -realtime -s msiexec.exe /x {26A24AE4-039D-4CA4-87B4-2F83217002F" +
            "F} /qr")]
        public string uninstall_02 {
            get {
                return ((string)(this["uninstall_02"]));
            }
            set {
                this["uninstall_02"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -i 1 -realtime -s msiexec.exe /x {26A24AE4-039D-4CA4-87B4-2F83217055F" +
            "F} /qr")]
        public string uninstall_55 {
            get {
                return ((string)(this["uninstall_55"]));
            }
            set {
                this["uninstall_55"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\fs1\\HelpDesk\\PLUGINS\\JAVA_55_MSI")]
        public string MSI_55_Location {
            get {
                return ((string)(this["MSI_55_Location"]));
            }
            set {
                this["MSI_55_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -s -i 1 -realtime msiexec /i c:\\temp\\JAVA_55_MSI\\jre1.7.0_55.msi /qr " +
            " JAVAUPDATE=0 JU=0 AUTOUPDATECHECK=0")]
        public string MSI_55_Argument {
            get {
                return ((string)(this["MSI_55_Argument"]));
            }
            set {
                this["MSI_55_Argument"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -i 1 -realtime -s msiexec.exe /x {26A24AE4-039D-4CA4-87B4-2F83217001F" +
            "F} /qr")]
        public string uninstall_01 {
            get {
                return ((string)(this["uninstall_01"]));
            }
            set {
                this["uninstall_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\temp\\JAVA_55_MSI")]
        public string MSI_55_Target {
            get {
                return ((string)(this["MSI_55_Target"]));
            }
            set {
                this["MSI_55_Target"] = value;
            }
        }
    }
}
