//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minion.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Flash : global::System.Configuration.ApplicationSettingsBase {
        
        private static Flash defaultInstance = ((Flash)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Flash())));
        
        public static Flash Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Flash")]
        public string name {
            get {
                return ((string)(this["name"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -realtime -h -c -f -csrc \"\\\\fs1\\HelpDesk\\PLUGINS\\Uninstallers\\uninsta" +
            "ll_flash_player.exe\" uninstall_flash_player.exe -uninstall")]
        public string uninstall_APP {
            get {
                return ((string)(this["uninstall_APP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -realtime -h -c -f -csrc \"\\\\fs1\\HelpDesk\\PLUGINS\\install_flash_player" +
            "_13_active_x.exe\" install_flash_player_13_active_x.exe -install -au 2")]
        public string install {
            get {
                return ((string)(this["install"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-realtime wmic product where \"name like \'Adobe Flash%%\'\" call uninstall /nointera" +
            "ctive")]
        public string uninstall_WMIC {
            get {
                return ((string)(this["uninstall_WMIC"]));
            }
        }
    }
}
