//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minion.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Reader : global::System.Configuration.ApplicationSettingsBase {
        
        private static Reader defaultInstance = ((Reader)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Reader())));
        
        public static Reader Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -realtime -h c:\\temp\\AdbeArCleaner.exe /silent /product=1")]
        public string uninstall_APP {
            get {
                return ((string)(this["uninstall_APP"]));
            }
            set {
                this["uninstall_APP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -realtime -h c:\\temp\\AdbeRdr11006_en_US.exe /sAll /msi /norestart ALL" +
            "USERS=1 EULA_ACCEPT=YES")]
        public string install {
            get {
                return ((string)(this["install"]));
            }
            set {
                this["install"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-accepteula -realtime -h wmic product where \"name like \'Adobe Reader%%\'\" call uni" +
            "nstall /nointeractive")]
        public string uninstall_WMIC {
            get {
                return ((string)(this["uninstall_WMIC"]));
            }
            set {
                this["uninstall_WMIC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\fs1\\HelpDesk\\PROGRAMS\\Adobe_Reader\\AdbeRdr11006_en_US.exe")]
        public string Install_Location {
            get {
                return ((string)(this["Install_Location"]));
            }
            set {
                this["Install_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\fs1\\HelpDesk\\PROGRAMS\\Adobe_Reader\\AdbeArCleaner.exe")]
        public string Uninstall_Location {
            get {
                return ((string)(this["Uninstall_Location"]));
            }
            set {
                this["Uninstall_Location"] = value;
            }
        }
    }
}
